### ISSUE TITLE
Error parsing XML literals

### ISSUE THREAD

**Issue by rsgoncalves** [phillord/hermit-reasoner#7]
The following error occurs when HermiT is dealing with (valid) XML literals. 

    2017-05-16 12:44:55.805 [Classification Thread] INFO  OWLReasonerManager    ------------------------------- Running Reasoner -------------------------------
    2017-05-16 12:44:55.866 [Classification Thread] INFO  OWLReasonerManager    
    2017-05-16 12:44:55.868 [Classification Thread] ERROR OWLReasonerManager    An error occurred during reasoning: javax/xml/stream/XMLStreamException.
    java.lang.NoClassDefFoundError: javax/xml/stream/XMLStreamException
    	at org.semanticweb.HermiT.datatypes.xmlliteral.XMLLiteral.parse(XMLLiteral.java:33) ~[na:na]
    	at org.semanticweb.HermiT.datatypes.xmlliteral.XMLLiteralDatatypeHandler.parseLiteral(XMLLiteralDatatypeHandler.java:45) ~[na:na]
    	at org.semanticweb.HermiT.datatypes.DatatypeRegistry.parseLiteral(DatatypeRegistry.java:105) ~[na:na]
    	at org.semanticweb.HermiT.model.Constant.create(Constant.java:111) ~[na:na]
    	at org.semanticweb.HermiT.structural.OWLClausification$DataRangeConverter.visit(OWLClausification.java:880) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLLiteralImplNoCompression.accept(OWLLiteralImplNoCompression.java:241) ~[na:na]
    	at org.semanticweb.HermiT.structural.OWLClausification$FactClausifier.visit(OWLClausification.java:959) ~[na:na]
    	at uk.ac.manchester.cs.owl.owlapi.OWLDataPropertyAssertionAxiomImpl.accept(OWLDataPropertyAssertionAxiomImpl.java:119) ~[na:na]
    	at org.semanticweb.HermiT.structural.OWLClausification.clausify(OWLClausification.java:250) ~[na:na]
    	at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:165) ~[na:na]
    	at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:208) ~[na:na]
    	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:199) ~[na:na]
    	at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:173) ~[na:na]
    	at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51) ~[na:na]
    	at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19) ~[na:na]
    	at org.protege.editor.owl.model.inference.ReasonerUtilities.createReasoner(ReasonerUtilities.java:20) ~[na:na]
    	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.ensureRunningReasonerInitialized(OWLReasonerManagerImpl.java:428) ~[na:na]
    	at org.protege.editor.owl.model.inference.OWLReasonerManagerImpl$ClassificationRunner.run(OWLReasonerManagerImpl.java:386) ~[na:na]
    	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_40]
    Caused by: java.lang.ClassNotFoundException: javax.xml.stream.XMLStreamException not found by org.semanticweb.hermit [27]
    	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556) ~[org.apache.felix.main.jar:na]
    	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77) ~[org.apache.felix.main.jar:na]
    	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993) ~[org.apache.felix.main.jar:na]
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
    	... 19 common frames omitted

**Comment by ignazio1977** [comment]
The missing class ships with most Oracle Java VMs (Java 7 and Java 8 at least).
Is this with Oracle Java or a different JVM?

**Comment by rsgoncalves** [comment]
I would think so as well... This happened with Oracle Java v1.8.0_40 (that ships with Protege 5.2).

**Comment by ignazio1977** [comment]
Uhm. Any chance of a corrupted jar in the download? Otherwise I can only think of OSGi rules kicking in and stopping access to that class.

**Comment by ignazio1977** [comment]
Bad package imports in the OSGi packaging. Fixed in version 1.4.2.456
